[project]
name = "2025-hackathon-challenge"
version = "0.1.0"
description = "Help Bruno survive the tasks from Professor CNOTworthy"
requires-python = ">=3.12"
dependencies = [
    "qiskit>=2.2.3",
]
